import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";


import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: "Communtity",
  description: "Generated by create next app",
  // icons: {
  //   icon: {
  //     url: '/images/logo.png',
  //     href: '/images/logo.png',
  //   },
  // },
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={poppins.className}>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
