import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Header from "@/components/Header";
config.autoAddCss = false;

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Communtity",
  description: "Generated by create next app",
  // icons: {
  //   icon: {
  //     url: '/images/logo.png',
  //     href: '/images/logo.png',
  //   },
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={poppins.className}>
        <Toaster
          toastOptions={{
            loading: {
              style: {
                background: "#FCE38A",
              },
            },
            success: {
              style: {
                background: "#95E1D3",
              },
            },
            error: {
              style: {
                background: "#F38181",
                color: "white",
              },
            },
          }}
        />
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
