// AUTHENTICATION
export const API_AUTHENTICATION_SERVICE =
  process.env.NEXT_PUBLIC_API_AUTHENTICATION_SERVICE;

// PROFILE
export const API_USER_PROFILE_SERVICE =
  process.env.NEXT_PUBLIC_API_USER_PROFILE_SERVICE;

// ADDITIONAL
export const API_UPLOAD_DOWNLOAD_SERVICE =
  process.env.NEXT_PUBLIC_API_UPLOAD_DOWNLOAD_SERVICE;
export const API_PUBLIC_TAG_SERVICE =
  process.env.NEXT_PUBLIC_API_PUBLIC_TAG_SERVICE;
export const API_PUBLIC_ROLE_SERVICE =
  process.env.NEXT_PUBLIC_API_PUBLIC_ROLE_SERVICE;

// CORE
export const API_CORE_PROJECT_SERVICE =
  process.env.NEXT_PUBLIC_API_CORE_PROJECT_SERVICE;
