export const workContentData = [
    {
        id: 1,
        company: "Harris",
        position: "DevOps Engineer",
        date: "20 May, 2023",
        location: "Bekasi, Indonesia",
        username: "Harris",
        avatar: "/assets/avatar.png",
        types: "Projects",
        duration: "Month",
        experience: "No experience",
        participation: "Remote",
        bg_color: "bg-CardTwo",
        is_saved: true,
    },
    {
        id: 2,
        company: "Amazon",
        position: "Cloud Engineer",
        date: "18 June, 2023",
        location: "Bandung, Indonesia",
        username: "Alexa",
        avatar: "/assets/avatar.png",
        types: "Projects",
        duration: "Year",
        experience: "> 1 Year",
        participation: "Onsite",
        bg_color: "bg-CardOne",
        is_saved: false,
    },
    {
        id: 3,
        company: "Google",
        position: "Backend Developer",
        date: "10 July, 2023",
        location: "Aceh, Indonesia",
        username: "Larry",
        avatar: "/assets/avatar.png",
        types: "Group",
        duration: "Day",
        experience: "No experience",
        participation: "Hybrid",
        bg_color: "bg-CardThree",
        is_saved: false,
    },
    {
        id: 4,
        company: "Tesla",
        position: "Frontend Developer",
        date: "25 May, 2023",
        location: "Bandung, Indonesia",
        username: "Elon",
        avatar: "/assets/avatar.png",
        types: "Events",
        duration: "Month",
        experience: "< 1 Year",
        participation: "Remote",
        bg_color: "bg-CardFour",
        is_saved: true,
    },
    {
        id: 5,
        company: "Facebook",
        position: "UI/UX Designer",
        date: "30 August, 2023",
        location: "Bekasi, Indonesia",
        username: "Mark",
        avatar: "/assets/avatar.png",
        types: "Projects",
        duration: "Year",
        experience: "> 1 Year",
        participation: "Onsite",
        bg_color: "bg-CardTwo",
        is_saved: true,
    },
    {
        id: 6,
        company: "Netflix",
        position: "Data Scientist",
        date: "15 April, 2023",
        location: "Aceh, Indonesia",
        username: "Hastings",
        avatar: "/assets/avatar.png",
        types: "Group",
        duration: "Day",
        experience: "No experience",
        participation: "Hybrid",
        bg_color: "bg-CardOne",
        is_saved: false,
    },
    {
        id: 7,
        company: "Microsoft",
        position: "Security Engineer",
        date: "11 July, 2023",
        location: "Bandung, Indonesia",
        username: "Bill",
        avatar: "/assets/avatar.png",
        types: "Projects",
        duration: "Month",
        experience: "> 1 Year",
        participation: "Remote",
        bg_color: "bg-CardThree",
        is_saved: false,
    },
    {
        id: 8,
        company: "Apple",
        position: "Full Stack Developer",
        date: "5 August, 2023",
        location: "Bekasi, Indonesia",
        username: "Steve",
        avatar: "/assets/avatar.png",
        types: "Projects",
        duration: "Year",
        experience: "< 1 Year",
        participation: "Onsite",
        bg_color: "bg-CardFour",
        is_saved: true,
    },
    {
        id: 9,
        company: "SpaceX",
        position: "Systems Engineer",
        date: "12 September, 2023",
        location: "Aceh, Indonesia",
        username: "Musk",
        avatar: "/assets/avatar.png",
        types: "Events",
        duration: "Day",
        experience: "No experience",
        participation: "Hybrid",
        bg_color: "bg-CardTwo",
        is_saved: true,
    },
    {
        id: 10,
        company: "Alibaba",
        position: "AI Engineer",
        date: "29 March, 2023",
        location: "Bandung, Indonesia",
        username: "Jack",
        avatar: "/assets/avatar.png",
        types: "Group",
        duration: "Month",
        experience: "< 1 Year",
        participation: "Remote",
        bg_color: "bg-CardOne",
        is_saved: false,
    },
    {
        id: 11,
        company: "Uber",
        position: "Mobile Developer",
        date: "3 May, 2023",
        location: "Bekasi, Indonesia",
        username: "Travis",
        avatar: "/assets/avatar.png",
        types: "Projects",
        duration: "Year",
        experience: "> 1 Year",
        participation: "Onsite",
        bg_color: "bg-CardThree",
        is_saved: true,
    },
    {
        id: 12,
        company: "Airbnb",
        position: "Frontend Engineer",
        date: "20 April, 2023",
        location: "Bandung, Indonesia",
        username: "Brian",
        avatar: "/assets/avatar.png",
        types: "Projects",
        duration: "Day",
        experience: "No experience",
        participation: "Hybrid",
        bg_color: "bg-CardFour",
        is_saved: false,
    },
    {
        id: 13,
        company: "Shopify",
        position: "Product Manager",
        date: "6 June, 2023",
        location: "Aceh, Indonesia",
        username: "Tobias",
        avatar: "/assets/avatar.png",
        types: "Group",
        duration: "Month",
        experience: "< 1 Year",
        participation: "Remote",
        bg_color: "bg-CardTwo",
        is_saved: false,
    },
    {
        id: 14,
        company: "Spotify",
        position: "DevOps Engineer",
        date: "19 September, 2023",
        location: "Bekasi, Indonesia",
        username: "Daniel",
        avatar: "/assets/avatar.png",
        types: "Events",
        duration: "Year",
        experience: "> 1 Year",
        participation: "Onsite",
        bg_color: "bg-CardOne",
        is_saved: true,
    },
    {
        id: 15,
        company: "TikTok",
        position: "Software Engineer",
        date: "22 July, 2023",
        location: "Bandung, Indonesia",
        username: "Zhang",
        avatar: "/assets/avatar.png",
        types: "Projects",
        duration: "Day",
        experience: "No experience",
        participation: "Hybrid",
        bg_color: "bg-CardThree",
        is_saved: true,
    },
];
